package:
  name: debks
  version: "1.0.1"

source:
  path: ./debks

build:
  entry_points:
    - DEBKS=debks.DEBKS_main:main
requirements:
  host:
    - python=3.7

  run:
    - python=3.7
    - scipy>=1.2.1
    - pysam>=0.15.2
    - pandas>=0.24.2
    - numpy>=1.16.6
    - docopt>=0.6.2

about:
  home: https://github.com/yangence/DEBKS
  license: GPL3
  summary: 'Analysis differential back-spliced in of ribo-zero RNA-seq'
